### ISSUE TITLE
Type 'Events' does not satisfy the constraint 'EventTemplateT'

### ISSUE THREAD

**Issue by leonardssh** [foxifyjs/events#7]
```ts
interface Events {
	foo: (bar: string) => void;
}

const eventEmitter = new EventEmitter<Events>(); 
```
```ts
Type 'Events' does not satisfy the constraint 'EventTemplateT'.
  Index signature for type 'string' is missing in type 'Events'.
```

**Typescript version**: `^4.5.4`

---

**UPDATE**:
Works only with direct assignment:
```ts
const eventEmitter = new EventEmitter<{ foo: (bar: string) => void }>();
```
![image](https://user-images.githubusercontent.com/35312043/149993289-be04efb1-4b88-495d-899b-edcb96db2d0d.png)

**UPDATE 2**:
The compiler is happy when that interface is extended from `EventTemplateT`, but its functionality stops working.
```ts
interface Events extends EventTemplateT {
	foo: (bar: string) => void;
}

const eventEmitter = new EventEmitter<Events>();
```
![image](https://user-images.githubusercontent.com/35312043/149994379-934ac673-f8f5-4f51-8299-53f69d581446.png)
![image](https://user-images.githubusercontent.com/35312043/149994169-32035ee9-f629-4934-93a1-131ac1f827fd.png)

**Comment by leonardssh** [comment]
I also tested with the nightly build, - localhost directly compiled, same problem.

**Comment by ardalanamini** [comment]
Hi @LeonardSSH
Firstly thank you for using this package and pointing out this issue.
I'll update the examples in the readme to point out the correct usage 👍🏻 

You can use `type` instead of `interface` to make it work properly, like this:
```typescript
type Events = {
	foo: (bar: string) => void;
}

const eventEmitter = new EventEmitter<Events>();
```

This issue is due to the usage of the class type parameter which enforces that the correct template is passed to the class using `extends` in the `EventEmitter` generic class.
